package builder

const tmplMain = `// Code generated by {{.CorePkg.Path}}/plugins/builder. DO NOT EDIT.
package main

import (
	core "{{.CorePkg.Path}}"
)

func main() {
	core.RunAndExit()
}
`

const tmplPlugins = `// Code generated by {{.CorePkg.Path}}/plugins/builder. DO NOT EDIT.
package main

import (
	_ "{{.CorePkg.Path}}"
	{{range .Plugins}}
	_ "{{.Path}}"
	{{- end}}
)
`

const tmplGen = `//go:build ignore
// Code generated by {{.CorePkg.Path}}/plugins/builder. DO NOT EDIT.
package main

import (
	core "{{.CorePkg.Path}}"
	{{range .Plugins}}
	_ "{{.Path}}"
	{{- end}}
)

func main() {
	core.GenAndExit()
}
`
