package builder

const tmplMain = `Code generated by github.com/launchrctl/launchr/plugins/builder. DO NOT EDIT.
//{% // Use "print" to prevent triggering "go generate" inside the project %}
{{ print "//go:generate go run ./gen.go " .Cwd }}
package main

import (
	"os"
	"embed"

	"{{.CorePkg.Path}}"
	{{range .Plugins}}
	_ "{{.Path}}"
	{{- end}}
)

//go:embed assets/*
var assets embed.FS

func main() {
	launchr.SetAssetsStorage(assets)
	os.Exit(launchr.Run())
}
`

const tmplGen = `
//go:build ignore
//Code generated by github.com/launchrctl/launchr/plugins/builder. DO NOT EDIT.
package main

import (
	"os"

	"{{.CorePkg.Path}}"
	{{range .Plugins}}
	_ "{{.Path}}"
	{{- end}}
)

func main() {
	os.Exit(launchr.Gen())
}
`
