package builder

const tmplMain = `// Code generated by {{.CorePkg.Path}}/plugins/builder. DO NOT EDIT.
package main

import (
	"embed"

	core "{{.CorePkg.Path}}"
	{{range .Plugins}}
	_ "{{.Path}}"
	{{- end}}
)

//go:embed assets/*
var assets embed.FS

func main() {
	core.SetAssetsStorage(assets)
	core.RunAndExit()
}
`

const tmplPlugins = `// Code generated by {{.CorePkg.Path}}/plugins/builder. DO NOT EDIT.
//{{/* Next line starts with a comment to prevent triggering "go generate" inside the project. */}}
{{/**/}}//go:generate go run ./gen.go {{.Cwd}}
package main

import (
	_ "{{.CorePkg.Path}}"
	{{range .Plugins}}
	_ "{{.Path}}"
	{{- end}}
)
`

const tmplGen = `//go:build ignore
// Code generated by {{.CorePkg.Path}}/plugins/builder. DO NOT EDIT.
package main

import (
	core "{{.CorePkg.Path}}"
	{{range .Plugins}}
	_ "{{.Path}}"
	{{- end}}
)

func main() {
	core.GenAndExit()
}
`
