# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    paths:
      - \.pb\.go$
      - \.pb\.goclay\.go$
      - bin
      - vendor
      - var
      - tmp
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - \.pb\.go$
      - \.pb\.goclay\.go$
      - bin
      - vendor
      - var
      - tmp
      - third_party$
      - builtin$
      - examples$
