# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 10s
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
  golint:
    min-confidence: 0
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2
 
linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - unused
    - ineffassign
    - typecheck
    - dupl
    - goconst
    - gosec
    - goimports
    - gosimple
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
  exclude-files:
    - \.pb\.go$
    - \.pb\.goclay\.go$
  exclude:
#    # _ instead of err checks
#    - G104
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
