action:
  title: arguments
  description: Test passing options to executed command
  arguments:
    - name: arg1
      title: Argument 1
      description: Some additional info for arg
      required: true # false by default
    - name: arg2
      title: Argument 2
      description: Some additional info for arg
  options:
    - name: firstoption
      title: First option
      type: string
    - name: secondoption
      title: Second option
      description: Option to do something
      type: boolean
      default: false
    - name: thirdoption
      title: Third option
      type: string

runtime:
  type: container
  image: envvars:latest
  build:
    context: ./
  command:
    - sh
    - /action/main.sh
    - "{{ .arg1 }}"
    - "{{ .arg2 }}"
    - "{{ .firstoption|removeLineIfNil }}"
    - "{{ if not (isNil .secondoption) }}--secondoption={{ .secondoption }}{{ else }}{{ removeLine }}{{ end }}"
    - "{{ if isSet .thirdoption }}--thirdoption={{ .thirdoption }}{{else}}Third option is not set{{ end }}"
    - "{{ removeLineIfSet .thirdoption }}"
    - '{{ if not (isChanged "thirdoption")}}Third Option is not Changed{{else}}{{ removeLine }}{{ end }}'
    - '{{ removeLineIfChanged "thirdoption" }}'
    - '{{ if isChanged "thirdoption"}}Third Option is Changed{{else}}{{ removeLine }}{{ end }}'
    - '{{ removeLineIfNotChanged "thirdoption" }}'
