action:
  title: buildargs
  description: Test passing args to Dockerfile
  image: buildargs:latest
  build:
    context: ./
    args:
      USER_ID: {{ .current_uid }}
      GROUP_ID: {{ .current_gid }}
      USER_NAME: username
  command:
    - sh
    - /action/main.sh
