action:
  title: aliasaction
  description: Test alias definition

runtime:
  type: container
  image: buildargs:latest
  alias:
    - "alias1"
    - "alias2"
  command:
    - sh
    - /action/main.sh
