name: Tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_call:

jobs:
  test:
    name: Test on ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Linux / AMD64
            os: ubuntu-latest
          - name: Linux / ARM64
            os: ubuntu-24.04-arm
          - name: MacOS / ARM64
            os: macos-latest
          - name: Windows / AMD64
            os: windows-latest
            continue-on-error: true
          - name: Windows / ARM64
            os: windows-11-arm
            continue-on-error: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.continue-on-error || false }}
    steps:
      - uses: actions/checkout@v4

      - name: OS Info
        uses: ./.github/actions/os-info

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Prepare dependencies
        run: go mod download

      - name: Test
        run: |
          go test ./...
