name: Run tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test on ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Linux / AMD64
            os: ubuntu-latest
          - name: Linux / ARM64
            os: ubuntu-latest-arm64
          - name: MacOS / ARM64
            os: macos-latest
          - name: Windows / AMD64
            os: windows-latest
          - name: Windows / ARM64
            os: windows-latest-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Show OS and architecture info
        run: |
          echo "OS: ${{ runner.os }}"
          echo "Architecture: ${{ runner.arch }}"
          if [ "${{ runner.os }}" = "Windows" ]; then
            echo "%OS%"
            echo "%PROCESSOR_ARCHITECTURE%"
          else
            echo "$OSTYPE"
            echo "$(uname -m)"
          fi
          
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Prepare dependencies
        run: go mod download

      - name: Test
        run: go test ./...
